### PR TITLE
Libraries are submodules and new makefile

### PR DESCRIPTION
**Pull request by Sturla22**
Sorry for the seemingly unrelated commits in this PR... I got problems when adding tests which led me to move libraries to submodules and change the Arduino Makefile. The existing tests pass after the changes and it builds locally, let's see what Travis thinks of this :smile: 

- Created the initial test files for solenoids and knitter
- Made the tests execute the four variants (KH910, KH930 with Uno and Mega)
- Migrated the libraries to submodules, note that I had to pick versions carefully to be compatible with the existing code
  - [Adafruit MCP23008](https://github.com/adafruit/Adafruit-MCP23008-library) (v1.0.2)
  - [PacketSerial](https://github.com/bakercp/PacketSerial/) (v1.2.0)
  - [SerialCommand](https://github.com/kroimon/Arduino-SerialCommand) (master)
  - [SoftI2CMaster](https://github.com/todbot/SoftI2CMaster) (4dbc663)
- Migrated to another [Arduino Makefile](https://github.com/sudar/Arduino-Makefile)
- Updated docs and Travis configuration to reflect changes to the Makefile/development environment

I hope this isn't too radical but I figured I could address the issue @chris007de raised in #25 about the development environment not being ideal.

Some of the pros with these changes are:
 - C++ 11 support with newer Arduino IDE
 - It is easier to update libraries when they are not copied over, also makes it clearer what code is not maintained by this project
 - Simpler setup for the development environment

### CODE REVIEW

**Comment by chris007de** [comment]
Thanks a lot, this cleans the build environment a lot.
I'll clean the commit history with git sqash when merging the PR, no worries.
Did you test your changes on hardware as well? Just to make sure the libraries in the submodules (and the newer Arduino version) still work the same way as our old includes.

**Comment by Sturla22** [comment]
That sounds great that you'll clean this up. I haven't tested on hardware yet.. Might have to solicit some help for that since I don't have a machine myself. I'll get back to you on that.

**Comment by Sturla22** [comment]
I have checked on hardware now and everything seems to be in order. However, compiling and flashing via the Arduino IDE seems to be broken after the move to submodules. This then raises the question whether supporting that can be discarded in favour of a more sane approach to library management.

As I have mentioned before, I think moving firmware updating into the AYAB GUI would be of great help to the less technical users, that would also remove the need to support the Arduino IDE.

Thoughts?

**Comment by chris007de** [comment]
> I have checked on hardware now and everything seems to be in order. However, compiling and flashing via the Arduino IDE seems to be broken after the move to submodules. This then raises the question whether supporting that can be discarded in favour of a more sane approach to library management.

I have no reservations against dropping support for compilation in Arduino IDE, as most users use precompiled binaries anyway. For developers, a Makefile is a well-known and solid way to build stuff. So I am totally fine with this.

> As I have mentioned before, I think moving firmware updating into the AYAB GUI would be of great help to the less technical users, that would also remove the need to support the Arduino IDE.
> 
> Thoughts?

I dont' know if I get you right, but there is already the possibility to flash a binary within the AYAB GUI (Tools -> Flash AYAB Firmware). Ther e you have the possibility to flash one of the binaries which are shipped with the GUI. Is this what you proposed?

If there are no more open points regarding the Makefile/Library issue, I'll merge the PR.

**Comment by Sturla22** [comment]
> there is already the possibility to flash a binary within the AYAB GUI (Tools -> Flash AYAB Firmware).

Ah I didn't know that, great!

> If there are no more open points regarding the Makefile/Library issue, I'll merge the PR.

I just realised that I have only tested the KH910 variant with the Uno (the only hardware I can get access to, I may get access to other variants at some point). 

So I have not tested the SoftI2CMaster library version that I checked out in that submodule.

- Do you think that is sufficient?
- If not, how should we test the other variants?
- Do you have a method for testing on hardware to make sure everything is working as expected?

**Comment by chris007de** [comment]
> I just realised that I have only tested the KH910 variant with the Uno (the only hardware I can get access to, I may get access to other variants at some point).
> 
> So I have not tested the SoftI2CMaster library version that I checked out in that submodule.
> 
> * Do you think that is sufficient?
> * If not, how should we test the other variants?
> * Do you have a method for testing on hardware to make sure everything is working as expected?

I'd say that's sufficient for now. Arduino Uno is by far the most used platform. Mega is still used by some, but we'll take the risk. I do not expect any difference in behaviour between KH910 and KH930.

There is no documented "run-in" test with hardware, so just trying some simple pattern and check if all needles are set correctly was how we checked if everything is still working correctly :-/

So...let's merge.

**Comment by Sturla22** [comment]
Alright, sounds good!

**Pull request merged**
