### PR TITLE
Restructure libraries folder and imports to work with Arduino IDE 1.8.*

### PR DESCRIPTION
**Pull request by clholgat**
More context: https://github.com/arduino/Arduino/issues/5186

### CODE REVIEW

**Comment by t0mpr1c3** [comment]
Thanks. This must be the dumbest breaking change in a mature IDE that I have ever seen.

**Comment by clholgat** [comment]
No problem. 

I'm new to this process, what are the next steps to actually submit this?

**Comment by chris007de** [comment]
> I'm new to this process, what are the next steps to actually submit this?

By creating this Pull Request, you basically submitted it to be reviewed.
If the changes are reasonable, we'll just accept the PR and it gets automatically merged into the target branch.

Speaking of branches: Is it your intention to get this merged to the master branch?
Current development happens on https://github.com/AllYarnsAreBeautiful/ayab-firmware/tree/v1.0-dev

**Comment by clholgat** [comment]
Y'all don't have a getting started or committing guide. I'll check out that branch and see what's up.

**Comment by chris007de** [comment]
> Y'all don't have a getting started or committing guide. I'll check out that branch and see what's up.

Good point ... I filed an issue for this in firmware and desktop repo #45 https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/425

**Comment by chris007de** [comment]
Hi @clholgat, any news on this PR? :)

**Comment by Tuuleh** [comment]
Is there anyone left still to review and merge these? I'm gonna check out @clholgat's fork for now but would be really nice to get this merged if it's ready.

**Comment by chris007de** [comment]
> Is there anyone left still to review and merge these? I'm gonna check out @clholgat's fork for now but would be really nice to get this merged if it's ready.

@Tuuleh thanks for bringing this up. Did you already use @clholgat's branch successfully? If yes, I'll merge it right away, please let me know.
After that, the next step would be to bring these changes also to our v1.0-dev branch, as this is the one where the current development is contained.

**Comment by Tuuleh** [comment]
I've used it successfully by flashing through the arduino IDE. The only specifics (which I think are not specific to their fork) were that:

- The local directory needs to be called `ayab` - maybe there are some absolute file paths, would be cool if it supported any directory name as I had this repo cloned into `ayab` and then needed to delete/move in order to clone another repo into the directory with the right name
- I needed to declare machine type in order to compile in the arduino IDE and so on my local machine added `#define KH930` to `settings.h`. 

It seems to work fine :) I knitted some colorwork yesterday. I have had some small hiccups with my ayab installation but I don't think it's because of the firmware (It's for sure because of my amateurish soldering)

What's the status of the project overall? Maybe there's some thread / website where I could read some more about that? Is there some entity that is responsible for the project or a handful of volunteers maintaining, whether there's an active roadmap and how one might contribute etc. I have a new job since last week and because of that I'm rather busy learning Scala right now but might also wanna contribute to ayab if I find some time (or as I find that I'd like some feature :smile: ).

**Comment by chris007de** [comment]
>     * The local directory needs to be called `ayab` - maybe there are some absolute file paths, would be cool if it supported any directory name as I had this repo cloned into `ayab` and then needed to delete/move in order to clone another repo into the directory with the right name

That requirement comes from Arduino IDE, this can't be influenced by the project afaik.

>     * I needed to declare machine type in order to compile in the arduino IDE and so on my local machine added `#define KH930` to `settings.h`.

This is addressed in the 1.0-dev branch. There, we don't build a firmware image for each and every machine type. It's now possible to choose the machine type during initialization.

> What's the status of the project overall?

Speaking of 1.0-dev... mainly @t0mpr1c3 spent a whole lot of work over a year ago in pushing forward to a "1.0" version of AYAB. The progress is tracked in https://github.com/AllYarnsAreBeautiful/ayab-desktop/milestone/14. The latest state of the project is basically described in https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/401#issuecomment-935148513
So yes, there is kind of a roadmap :) Would be great if you could spare some time to help bringing the 1.0 release forward!
Just pick some topic you would like to work on and/or ask further questions where to start, we'll be happy to assist!

**Review by chris007de — APPROVED** [review]

**Pull request merged**
